### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by Chrisdt95** [Ziloka/ProxyBroker#4]
For some reason, the checker command doesn't work, the grab command doesn't work, it doesn't show the types of proxies that its getting.

**Comment by ziloka** [comment]
oh okay, will be noted, also fyi it grabs duplicate proxies for some weird reason

**Comment by ziloka** [comment]
there i've.. recreated the release (shouldn't have done that and probably should've made another release) but I believe it should be fixed now

**Comment by ziloka** [comment]
i mean besides displaying the protocol of said proxies

**Comment by ziloka** [comment]
commit 53753dd2393fb1094e4ab94e8bbe81584cf2e6f2 should fix this
